Add ioctl functions
rt-net/RaspberryPiMouse pull request #24
Opened 2020-01-30 10:02 UTC by haraisao

Add ioctl functions: led,, buzzer, sensor, motor and counter

2020-02-04 05:51 UTC, ShotaAk requested changes
レビューしました。指摘項目については修正 or コメントをお願いします。

また、何箇所か構造体を使うことを提案しています。これについて、もし採用する場合は別PRでお願いします。

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +
led_statusをここで宣言すると、変数の宣言が１箇所にまとまるので良いです。

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +static unsigned char led_status[N_LEDS];
led_statusをファイル上部で宣言すると、変数の宣言が１箇所にまとまるので良いです。

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.h
> +#define IOCTL_MOTOR_SP   3
_IO マクロを使った方が良さそうですが、
デバイス指定でopenすることより、コマンドは被らないのでこのままにします。

https://github.com/raspberrypi/linux/blob/rpi-4.19.y/Documentation/ioctl/ioctl-number.txt

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +   return 0;
インデントが崩れてるので修正お願いします。

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +  unsigned char val[4];
定数 N_LEDSを使ってください。

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +        for(i=0; i< 4; i++){
定数 N_LEDSを使ってください。

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +        }
インデント修正お願いします。（他にもいくつかあるのでエディタの問題？）

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +static int sens_val[N_SENSORS];
他の変数と同様に、ファイル上部で宣言してください。

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +	cval = *((int *)fp->private_data);
cval は使われないので削除できますか？

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +	  /* set sensor data to rw_buf(static buffer) */
このコメントは不要です

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +        memset(led_status, 0, sizeof(unsigned char) * 4);
N_LEDSを使ってください。

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +static long sensor_ioctl(struct file *fp, unsigned int cmd, unsigned long arg)
提案ですが、

どのセンサの値を読み取っているのかわかりやすくするため、
構造体で値の受け渡しをできないでしょうか？

```c
// ユーザコードの例
strcut sensor_values sens;
ret = ioctl(fd, IOCTL_READ, &sens);

sens.r;
sens.rf;
```

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +	int motor_cmd[3]; // motor_l, motor_r, time
提案ですが、

モータコマンドの入力をわかりやすくするため、
構造体で値の受け渡しをできないでしょうか？

```c
// ユーザコードの例
struct motor_cmd cmd;
cmd.l_freq = 100;
cmd.r_freq = 500;
cmd.time = 1000;
ret = ioctl(fd, IOCTL_MOTOR_CMD, &cmd);
```

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +		case IOCTL_MOTOR_SP: //set motor_cal
IOCTL_MOTOR_SPは何の略かわからないので変更お願いします。
（MOTOR_SPEED?）

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.c
> +static long counter_ioctl(struct file *fp, unsigned int cmd, unsigned long arg)
提案ですが、

カウンタのL、Rをわかりやすくするため、
構造体で値の受け渡しをできないでしょうか？

```c
// ユーザコードの例
struct counter cnt;
ret = ioctl(fd, IOCTL_READ, &cmd);
cnt.r;
cnt.l;
```

2020-02-04 05:51 UTC, ShotaAk commented on src/drivers/rtmouse.h
> +#define SENS_INTVAL 30
SENS_INTVALはユーザが使わないと思うので、ソースファイルに隠すのはどうでしょうか？

2020-02-14 19:51 UTC, haraisao commented on src/drivers/rtmouse.c
> +
そうですね。修正いたします。

2020-02-14 19:55 UTC, haraisao commented on src/drivers/rtmouse.c
> +	int motor_cmd[3]; // motor_l, motor_r, time
モータコマンドは、構造体の方がユーザのミスが少なくなりますので、構造体に修正します。

2020-02-14 19:56 UTC, haraisao commented on src/drivers/rtmouse.c
> +		case IOCTL_MOTOR_SP: //set motor_cal
ご推察のとおりMOTOR_SPEEDのことです。修正いたします。

2020-02-14 20:00 UTC, haraisao commented on src/drivers/rtmouse.h
> +#define SENS_INTVAL 30
SENS_INTVALは、ユーザ空間では使いませんので、ソースファイルに移行します。

2020-02-14 20:02 UTC, haraisao commented on src/drivers/rtmouse.c
> +static long counter_ioctl(struct file *fp, unsigned int cmd, unsigned long arg)
モータへの対応も考えるとご提案の方がよいですね。修正いたします。

2020-02-14 20:04 UTC, haraisao commented on src/drivers/rtmouse.c
> +static long sensor_ioctl(struct file *fp, unsigned int cmd, unsigned long arg)
ユーザにわかりやすい方が良いので、ご提案の通り修正します。

2020-02-14 20:05 UTC, haraisao commented on src/drivers/rtmouse.c
> +  unsigned char val[4];
承知しました。修正します。

2020-02-14 20:05 UTC, haraisao commented on src/drivers/rtmouse.c
> +   return 0;
修正いたします。

2024-09-20 06:40 UTC, ShotaAk commented
PR作成から時間が経過したため一旦クローズします。
ioctl機能を取り入れることになったらまた参照します。

2024-09-20 06:40 UTC, closed without merging