Create README.md
rt-net/RaspberryPiMouse pull request #28
Opened 2020-02-04 09:32 UTC by ShotaAk

SampleProgramディレクトリにREADMEを追加しました。

2020-02-07 02:54 UTC, Tiryoh requested changes

2020-02-07 02:54 UTC, Tiryoh commented on SampleProgram/README.md
> +Each peripheral example have sample code files written Shell Script, C and Python.
s/Each peripheral example have/Each peripheral example has/
だと思います。

2020-02-07 02:54 UTC, Tiryoh commented on SampleProgram/README.md
> +組み合わせは次のとおりです
s/次のとおりです/次のとおりです。/
ほかが句読点を含んでいるので統一したらいいと思います。

2020-02-07 02:54 UTC, Tiryoh reviewed
`Type [Ctrl-c] to terminate.`など「Type [key]」という表記が複数見られますが、`Press [Ctrl-c] to terminate.`など「Press [key]」の方がわかりやすいのではないかと思います。
type [Ctrl-c]と言われると、"C", "t", "r", "l"...と入力していくようなイメージがあります。

実際に「type ctrl c」などでググると「press ctrl c」がヒットしますし、以下のリポジトリではpressが使用されているので、typeよりはpressの方がよい気がします。
https://github.com/vim-ctrlspace/vim-ctrlspace

これについてはコードの変更も含むので、別issueを立てます。

2020-02-07 04:14 UTC, ShotaAk commented
> `Type [Ctrl-c] to terminate.`など「Type [key]」という表記が複数見られますが、`Press [Ctrl-c] to terminate.`など「Press [key]」の方がわかりやすいのではないかと思います。
> type [Ctrl-c]と言われると、"C", "t", "r", "l"...と入力していくようなイメージがあります。
> 
> 実際に「type ctrl c」などでググると「press ctrl c」がヒットしますし、以下のリポジトリではpressが使用されているので、typeよりはpressの方がよい気がします。
> https://github.com/vim-ctrlspace/vim-ctrlspace
> 
> これについてはコードの変更も含むので、別issueを立てます。

ありがとうございます。TypeとPressの使い分けを理解しました。
issue立てもありがとうございます。

2020-02-07 04:23 UTC, ShotaAk commented
修正しました。

2020-02-07 06:04 UTC, Tiryoh requested changes
先ほどは最後の方いくつか読み飛ばしてしまっていたので追記しました

2020-02-07 06:04 UTC, Tiryoh commented on SampleProgram/README.md
> +Refer the [./SCALE](./SCALE) file for the pairs of input characters and scales.
s/Refer the/Refer to the/
だと思います。

2020-02-07 06:04 UTC, Tiryoh commented on SampleProgram/README.md
> +The pairs of LEDs and switches are bellow:
The combination of LEDs and switches are defined as below.
とかどうでしょうか。

2020-02-07 08:06 UTC, ShotaAk commented
修正しました

2020-02-12 05:01 UTC, Tiryoh approved these changes

2020-02-12 05:02 UTC, merged