Change indents of TAB (space x8) to space x4 in sample scripts.
rt-net/RaspberryPiMouse pull request #29
Opened 2020-02-06 07:58 UTC by ShotaAk

PythonのサンプルスクリプトがTAB(スペース8つ分)でインデントされていたので、
スペース4つのインデントにしました。

これにより　#27 の不具合も修正されます。

pytnon2.7とpython3.6 で動作確認しています。

2020-02-07 02:37 UTC, Tiryoh reviewed
committerとauthorが適切に設定されていないようですが、気にせずこのままにしますか？

2020-02-07 04:25 UTC, ShotaAk commented
あれ？？？？
直します。

2020-02-07 05:53 UTC, Tiryoh requested changes
ぱっと見て気になるところコメント付けました。
プルリクエストのタイトルを「リファクタリング」などにしてインデントの変更だけではなく、そのほかもflake8で警告が出ないように修正するのはいかがでしょうか。

2020-02-07 05:53 UTC, Tiryoh commented on SampleProgram/step2.py
> +        import sys,tty,termios
2行目ですでにimportしたものも含まれているので、そのほかのパッケージについても2行目でimportすればいいと思います。

2020-02-07 05:53 UTC, Tiryoh commented on SampleProgram/step2.py
> +        import tty,sys
`__call__`で使うパッケージと同じなので2行目でまとめてimportすればいいと思います。

2020-02-07 07:22 UTC, ShotaAk commented
> ぱっと見て気になるところコメント付けました。
> プルリクエストのタイトルを「リファクタリング」などにしてインデントの変更だけではなく、そのほかもflake8で警告が出ないように修正するのはいかがでしょうか。

賛成です。
pycodestyleでやります。

2020-02-07 08:00 UTC, ShotaAk commented
修正しました。

2020-02-12 05:00 UTC, Tiryoh approved these changes

2020-02-12 05:02 UTC, merged