Add step4, step5 samples
rt-net/RaspberryPiMouse pull request #32
Opened 2020-03-26 08:35 UTC by ShotaAk

モータを回すサンプルと、ライトセンサの値を読むサンプルを追加しました。

2020-04-03 10:16 UTC, Tiryoh commented
確認することリスト

- [ ] step4.c
- [ ] step4.sh
- [ ] step4.py
- [ ] step5.c
- [ ] step5.sh
- [ ] step5.py

2020-04-03 10:25 UTC, Tiryoh commented on SampleProgram/step5.py
> +        print(f.read())
`step5.sh`を実行すると、
```
$ bash step5.sh
13 9 69 42
14 9 69 40
14 8 67 40
13 10 69 43
12 8 68 43
14 8 67 42
13 8 68 41
```
と１行ずつセンサ値が表示されます。
しかし、`step5.py`では１行開けてセンサ値が表示されています。
```
$ python step5.py 
12 7 68 40

14 7 65 43

13 8 68 40

14 7 66 42

^CTraceback (most recent call last):
  File "step5.py", line 7, in <module>
    time.sleep(0.5)
KeyboardInterrupt
```

どちらかに統一したほうがサンプルとしては見やすいと思います。
１行開けないためには、以下のようにデバイスファイルの読み込み時に改行を削除するか、`print`時に改行を入れないのどちらかがあると思います。

```
        print(f.read().strip())
```

2020-04-03 10:28 UTC, Tiryoh requested changes

2020-04-03 10:28 UTC, Tiryoh commented on SampleProgram/step5.c
> +#include <fcntl.h>
```suggestion
#include <fcntl.h>
#include <unistd.h>
```

今のままコンパイルすると`usleep`の部分でワーニングが出ます。コンパイラがいいように解釈してくれているようですが、環境依存になってしまうので、必要なヘッダファイルを入れたほうが良さそうです。

```
$ gcc step5.c -o step5
step5.c: In function ‘main’:
step5.c:17:9: warning: implicit declaration of function ‘usleep’; did you mean ‘fseek’? [-Wimplicit-function-declaration]
         usleep(500*1000);
         ^~~~~~
         fseek
```

`gcc`のバージョンは下記のとおりです。

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 
```

2020-04-03 10:35 UTC, Tiryoh requested changes

2020-04-03 10:35 UTC, Tiryoh commented on SampleProgram/step5.c
> +	    }
スペースとタブが混ざっているようです。ほかがスペースでインデントされているのでスペースに統一するのが望ましいと思います。

```suggestion
            while(fgets(buff, buff_size, fp) != NULL){
                printf("%s\n", buff);
            }
```

![Screenshot from 2020-04-03 19-31-39](https://user-images.githubusercontent.com/3256629/78351713-34603380-75e2-11ea-9b8c-03d090c35cd1.png)

2020-04-06 05:32 UTC, ShotaAk commented
step5を修正しました。

2020-04-06 07:46 UTC, Tiryoh commented
実機にて動作確認しました

2020-04-06 07:47 UTC, Tiryoh approved these changes
実機にて動作確認しました

2020-04-06 07:47 UTC, merged