Add step6 sample
rt-net/RaspberryPiMouse pull request #41
Opened 2020-04-09 07:03 UTC by ShotaAk

パルスカウンタ値を読み取るサンプルを追加しました。

2020-04-09 07:10 UTC, ShotaAk commented
#26

2020-04-10 11:01 UTC, Tiryoh requested changes

2020-04-10 11:01 UTC, Tiryoh commented on SampleProgram/step6.sh
> +reset_counter
`reset_counter`は定義されていないようです。

```suggestion
reset_counters_and_motors
sleep 0.1
```

2020-04-13 01:24 UTC, ShotaAk commented on SampleProgram/step6.sh
> +reset_counter
修正しました。

2020-04-13 06:39 UTC, Tiryoh approved these changes
lgtm

2020-04-13 06:40 UTC, merged