Migrate to GitHub Actions
rt-net/RaspberryPiMouse pull request #44
Opened 2020-04-13 08:10 UTC by Tiryoh

2020-04-15 08:47 UTC, ShotaAk requested changes
チェックしました。コメントを残したので確認お願いします。

キャッシュ機能については後ほど追加で良いと思います。（挑戦した痕跡が見えたので）

2020-04-15 08:47 UTC, ShotaAk commented on .github/workflows/driver-cross-build.yml
> +  WORKSPACE: /home/runner
使われていないので削除してください。

2020-04-15 08:47 UTC, ShotaAk commented on .github/workflows/driver-cross-build.yml
> +          echo "::set-output name=repository-dir::$(echo ${GITHUB_WORKSPACE})"
ここでset-outputし各stepで環境変数を設定してますが必要でしょうか？
たとえば${REPOSITORY_DIR}としているところはそのまま${GITHUB_WORKSPACE}に置き換えられそうです。

2020-04-15 09:34 UTC, Tiryoh commented
キャッシュについてはあまり効果が見られなかったので一度削除しました。今までとはことなり、ドライバ以外（サンプルプログラム等）の更新ではこのテストは走らないので、キャッシュが必要そうであれば今後検討したいと思います。

キャッシュあり：https://github.com/rt-net/RaspberryPiMouse/runs/582341544
キャッシュなし：https://github.com/rt-net/RaspberryPiMouse/runs/584337873

2020-04-16 04:23 UTC, ShotaAk commented
キャッシュしても5分しか変わらないのか・・・

2020-04-16 04:26 UTC, ShotaAk approved these changes
良いと思います

2020-04-16 04:26 UTC, merged